from app import db,models
import datetime
l1 = models.Location(name='University', address='Roger Stevens')
b1 = models.Bike(current_location=1)
l2 = models.Location(name='City', address='Headrow')
b2 = models.Bike(current_location=2)
l3 = models.Location(name='Headingley', address='Otley Road')
b3 = models.Bike(current_location=3)
b4 = models.Bike(current_location=1)
b5 = models.Bike(current_location=1)
b6 = models.Bike(current_location=2)
b7 = models.Bike(current_location=2)
b8 = models.Bike(current_location=3)
b9 = models.Bike(current_location=3)
db.session.add(l1)
db.session.add(b1)
db.session.add(l2)
db.session.add(b2)
db.session.add(l3)
db.session.add(b3)
db.session.add(b4)
db.session.add(b5)
db.session.add(b6)
db.session.add(b7)
db.session.add(b8)
db.session.add(b9)
db.session.commit()
